### PR TITLE
candidate f64 support

### PR DESCRIPTION
**Pull request by rustysec**
I ran into a situation where I needed floating point support and ended up doing some hacking around with string passing and converting outside of the Rhai script. Then I was looking through the issues and noticed #28, thought I'd take a crack at it. Basically this short circuits the token parsing to add an additional literal type that starts with "f" and attempts to treat it like a float (f64 only at this point). There are probably some more efficient or elegant ways to do this, but I didn't want to mess with the rest of the parsing engine unless this solution is not acceptable.

an example of usage would be
```
let x = f1_0;
let y = f1_1;
print(x < y)
```
which will yield true. i added some test cases around the floats and all others are passing as well. i'm completely open to re-implementing this a different way.

### CODE REVIEW

**Comment by rustysec** [comment]
This does have the downside of shadowing valid variable names.
```rust
let f1 = 10;
let x = f1;
print(x)
```
will print `10` instead of `1` like you might expect.

**Comment by luciusmagn** [comment]
hmm, apart from the syntax, I like the changes. Maybe we could look into parsing floats with a familiar syntax? 

Line 273 in [parser.rs](https://github.com/jonathandturner/rhai/blob/master/src/parser.rs#L273) is where we parse (at the moment) integer literals. Since our TokenIterator can do peeking, maybe we could peek if there is a dot after the last digit and if yes, try parsing digits behind it.

Let's ask @jonathandturner for his opinion on this, too.

**Comment by rustysec** [comment]
I agree, the more I've used it the more I'm convinced I need to rework the syntax. I'll submit a different candidate tonight or tomorrow.

**Comment by rustysec** [comment]
Pushed a more sane implementation with very standard syntax and without the token name collision I mentioned above.
```rust
let x = 1.99;
let y = 2.00;
print(x < y);
```
will produced the desired `true`.

**Comment by luciusmagn** [comment]
This is exactly what I had in mind. Could you try resolving the conflicts in src/tests.rs created after I merged your stringly += PR? I could merge, then

**Comment by luciusmagn** [comment]
Lovely, merging!

**Pull request merged**
