### PR TITLE
License clarification

### LINKED ISSUE #193: License clarification
Hi - LICENSE.txt contains only Apache 2.0, but Cargo.toml says `license = "MIT OR Apache-2.0"`. Please clarify.

### PR DESCRIPTION
**Pull request by felixrabe**
Closes #193.

### CODE REVIEW

**Comment by felixrabe** [comment]
IANAL / take with salty grains. This is based on my interpretation that Cargo.toml's `license = "MIT OR Apache-2.0"` defines the project's intended license.

**Comment by schungx** [comment]
Will renaming the files away from `LICENSE.txt` cause Github to complain not having a license again?

**Comment by felixrabe** [comment]
Judging from https://github.com/dtolnay/syn and [GitHub Docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license) (-> [Licensee Gem](https://github.com/licensee/licensee#documentation) -> [what it looks at](https://github.com/licensee/licensee/blob/aa9bec625601c05db574b0c84af2bf716d97717e/lib/licensee/project_files/license_file.rb)) I guess you'll get a "View license" link pointing to LICENSE-APACHE.txt.

**Comment by felixrabe** [comment]
Yes it will - changed default branch to this PR and https://github.com/felixrabe/rhai does that.

**Comment by felixrabe** [comment]
Idea for a future pull request for further clarification:

There are crates using a COPYING / COPYRIGHT file that points to both licenses, and "View license" will prefer that.

**Comment by felixrabe** [comment]
Last comment :) - see https://github.com/mun-lang/mun for an example of the above.

**Pull request merged**
